scnShortcodeMeta={
	attributes:[
		{
			label:"Title",
			id:"title",
            help:"",
			isRequired:true
		},
        {
		label:"Link",
		id:"link",
		
   		 },
        {
			label:"Select icon",
			id:"icon",
			help:"",
            controlType:"select-control", 
			selectValues:[
                'none',
                ' icon-glass',
                ' icon-heart',
                ' icon-film',
                ' icon-ok',
                ' icon-off',
                ' icon-home',
                ' icon-download-alt',
                ' icon-play-circle',
                ' icon-lock',
                ' icon-volume-down',
                ' icon-tag',
                ' icon-print',
                ' icon-italic',
                ' icon-align-center',
                ' icon-indent-left',
                ' icon-pencil',
                ' icon-edit',
                ' icon-step-backward',
                ' icon-pause',
                ' icon-step-forward',
                ' icon-plus-sign',
                ' icon-question-sign',
                ' icon-ok-circle',
                ' icon-arrow-up',
                ' icon-resize-small',
                ' icon-exclamation-sign',
                ' icon-eye-open',
                ' icon-calendar',
                ' icon-chevron-up',
                ' icon-folder-close',
                ' icon-hdd',
                ' icon-thumbs-up',
                ' icon-hand-up',
                ' icon-circle-arrow-up',
                ' icon-tasks',
                ' icon-filter',
                ' icon-circle-arrow-down',
                ' icon-hand-down',
                ' icon-thumbs-down',
                ' icon-bullhorn',
                ' icon-folder-open',
                ' icon-chevron-down',
                ' icon-random',
                ' icon-eye-close',
                ' icon-gift',
                ' icon-plus',
                ' icon-arrow-down',
                ' icon-ban-circle',
                ' icon-info-sign',
                ' icon-minus-sign',
                ' icon-eject',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                ''
                
            
            
            
            ]
        },
         {
		label:"Submenu?",
		id:"submenu",
		help:"", 
		controlType:"select-control", 
		selectValues:['no','yes']
   		 }
		],
		defaultContent: " ",
		shortcode:"dropdown_element"
		
};